#
# Run:
#   docker compose run --rm ixnetwork

#version: "3"
services:
  ixnetwork:
    platform: linux/amd64
    privileged: true
    build:
      context: .
    image: ghcr.io/daddy-knows-ixnetwork/ixnetwork:main
    volumes:
      # For future ssh use in development
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - .:/IxNetwork
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
      #- /var/run/docker.sock:/var/run/docker.sock
      #- ~/.kube:/home/ubuntu/.kube_host:ro
      #environment:
    working_dir: /IxNetwork
